// src/data/countries.js
// Spisak država sveta sa Unicode zastavama

const countries = {
  "AF": { name: "Afganistan", flag: "🇦🇫" },
  "AL": { name: "Albanija", flag: "🇦🇱" },
  "DZ": { name: "Alžir", flag: "🇩🇿" },
  "AD": { name: "Andora", flag: "🇦🇩" },
  "AO": { name: "Angola", flag: "🇦🇴" },
  "AR": { name: "Argentina", flag: "🇦🇷" },
  "AM": { name: "Jermenija", flag: "🇦🇲" },
  "AU": { name: "Australija", flag: "🇦🇺" },
  "AT": { name: "Austrija", flag: "🇦🇹" },
  "AZ": { name: "Azerbejdžan", flag: "🇦🇿" },
  "BH": { name: "Bahrein", flag: "🇧🇭" },
  "BD": { name: "Bangladeš", flag: "🇧🇩" },
  "BY": { name: "Belorusija", flag: "🇧🇾" },
  "BE": { name: "Belgija", flag: "🇧🇪" },
  "BZ": { name: "Beliz", flag: "🇧🇿" },
  "BJ": { name: "Benin", flag: "🇧🇯" },
  "BT": { name: "Butan", flag: "🇧🇹" },
  "BO": { name: "Bolivija", flag: "🇧🇴" },
  "BA": { name: "Bosna i Hercegovina", flag: "🇧🇦" },
  "BW": { name: "Bocvana", flag: "🇧🇼" },
  "BR": { name: "Brazil", flag: "🇧🇷" },
  "BG": { name: "Bugarska", flag: "🇧🇬" },
  "BF": { name: "Burkina Faso", flag: "🇧🇫" },
  "BI": { name: "Burundi", flag: "🇧🇮" },
  "KH": { name: "Kambodža", flag: "🇰🇭" },
  "CM": { name: "Kamerun", flag: "🇨🇲" },
  "CA": { name: "Kanada", flag: "🇨🇦" },
  "CV": { name: "Zelenortska Ostrva", flag: "🇨🇻" },
  "CF": { name: "Centralnoafrička Republika", flag: "🇨🇫" },
  "TD": { name: "Čad", flag: "🇹🇩" },
  "CL": { name: "Čile", flag: "🇨🇱" },
  "CN": { name: "Kina", flag: "🇨🇳" },
  "CO": { name: "Kolumbija", flag: "🇨🇴" },
  "KM": { name: "Komori", flag: "🇰🇲" },
  "CG": { name: "Kongo", flag: "🇨🇬" },
  "CD": { name: "Kongo (Dem. Rep.)", flag: "🇨🇩" },
  "CR": { name: "Kostarika", flag: "🇨🇷" },
  "HR": { name: "Hrvatska", flag: "🇭🇷" },
  "CU": { name: "Kuba", flag: "🇨🇺" },
  "CY": { name: "Kipar", flag: "🇨🇾" },
  "CZ": { name: "Češka", flag: "🇨🇿" },
  "DK": { name: "Danska", flag: "🇩🇰" },
  "DJ": { name: "Džibuti", flag: "🇩🇯" },
  "DM": { name: "Dominika", flag: "🇩🇲" },
  "DO": { name: "Dominikanska Republika", flag: "🇩🇴" },
  "EC": { name: "Ekvador", flag: "🇪🇨" },
  "EG": { name: "Egipat", flag: "🇪🇬" },
  "SV": { name: "El Salvador", flag: "🇸🇻" },
  "GQ": { name: "Ekvatorska Gvineja", flag: "🇬🇶" },
  "ER": { name: "Eritreja", flag: "🇪🇷" },
  "EE": { name: "Estonija", flag: "🇪🇪" },
  "SZ": { name: "Svaziland", flag: "🇸🇿" },
  "ET": { name: "Etiopija", flag: "🇪🇹" },
  "FJ": { name: "Fidži", flag: "🇫🇯" },
  "FI": { name: "Finska", flag: "🇫🇮" },
  "FR": { name: "Francuska", flag: "🇫🇷" },
  "GA": { name: "Gabon", flag: "🇬🇦" },
  "GM": { name: "Gambija", flag: "🇬🇲" },
  "GE": { name: "Gruzija", flag: "🇬🇪" },
  "DE": { name: "Nemačka", flag: "🇩🇪" },
  "GH": { name: "Gana", flag: "🇬🇭" },
  "GR": { name: "Grčka", flag: "🇬🇷" },
  "GD": { name: "Grenada", flag: "🇬🇩" },
  "GT": { name: "Gvatemala", flag: "🇬🇹" },
  "GN": { name: "Gvineja", flag: "🇬🇳" },
  "GW": { name: "Gvineja-Bisau", flag: "🇬🇼" },
  "GY": { name: "Gvajana", flag: "🇬🇾" },
  "HT": { name: "Haiti", flag: "🇭🇹" },
  "HN": { name: "Honduras", flag: "🇭🇳" },
  "HU": { name: "Mađarska", flag: "🇭🇺" },
  "IS": { name: "Island", flag: "🇮🇸" },
  "IN": { name: "Indija", flag: "🇮🇳" },
  "ID": { name: "Indonezija", flag: "🇮🇩" },
  "IR": { name: "Iran", flag: "🇮🇷" },
  "IQ": { name: "Irak", flag: "🇮🇶" },
  "IE": { name: "Irska", flag: "🇮🇪" },
  "IL": { name: "Izrael", flag: "🇮🇱" },
  "IT": { name: "Italija", flag: "🇮🇹" },
  "CI": { name: "Obala Slonovače", flag: "🇨🇮" },
  "JM": { name: "Jamajka", flag: "🇯🇲" },
  "JP": { name: "Japan", flag: "🇯🇵" },
  "JO": { name: "Jordan", flag: "🇯🇴" },
  "KZ": { name: "Kazahstan", flag: "🇰🇿" },
  "KE": { name: "Kenija", flag: "🇰🇪" },
  "KI": { name: "Kiribati", flag: "🇰🇮" },
  "KW": { name: "Kuvajt", flag: "🇰🇼" },
  "KG": { name: "Kirgistan", flag: "🇰🇬" },
  "LA": { name: "Laos", flag: "🇱🇦" },
  "LV": { name: "Letonija", flag: "🇱🇻" },
  "LB": { name: "Liban", flag: "🇱🇧" },
  "LS": { name: "Lesoto", flag: "🇱🇸" },
  "LR": { name: "Liberija", flag: "🇱🇷" },
  "LY": { name: "Libija", flag: "🇱🇾" },
  "LI": { name: "Lihtenštajn", flag: "🇱🇮" },
  "LT": { name: "Litvanija", flag: "🇱🇹" },
  "LU": { name: "Luksemburg", flag: "🇱🇺" },
  "MG": { name: "Madagaskar", flag: "🇲🇬" },
  "MW": { name: "Malavi", flag: "🇲🇼" },
  "MY": { name: "Malezija", flag: "🇲🇾" },
  "MV": { name: "Maldivi", flag: "🇲🇻" },
  "ML": { name: "Mali", flag: "🇲🇱" },
  "MT": { name: "Malta", flag: "🇲🇹" },
  "MH": { name: "Maršalska Ostrva", flag: "🇲🇭" },
  "MR": { name: "Mauritanija", flag: "🇲🇷" },
  "MU": { name: "Mauricijus", flag: "🇲🇺" },
  "MX": { name: "Meksiko", flag: "🇲🇽" },
  "FM": { name: "Mikronezija", flag: "🇫🇲" },
  "MD": { name: "Moldavija", flag: "🇲🇩" },
  "MC": { name: "Monako", flag: "🇲🇨" },
  "MN": { name: "Mongolija", flag: "🇲🇳" },
  "ME": { name: "Crna Gora", flag: "🇲🇪" },
  "MA": { name: "Maroko", flag: "🇲🇦" },
  "MZ": { name: "Mozambik", flag: "🇲🇿" },
  "MM": { name: "Mjanmar", flag: "🇲🇲" },
  "NA": { name: "Namibija", flag: "🇳🇦" },
  "NR": { name: "Nauru", flag: "🇳🇷" },
  "NP": { name: "Nepal", flag: "🇳🇵" },
  "NL": { name: "Holandija", flag: "🇳🇱" },
  "NZ": { name: "Novi Zeland", flag: "🇳🇿" },
  "NI": { name: "Nikaragva", flag: "🇳🇮" },
  "NE": { name: "Niger", flag: "🇳🇪" },
  "NG": { name: "Nigerija", flag: "🇳🇬" },
  "NO": { name: "Norveška", flag: "🇳🇴" },
  "OM": { name: "Oman", flag: "🇴🇲" },
  "PK": { name: "Pakistan", flag: "🇵🇰" },
  "PW": { name: "Palau", flag: "🇵🇼" },
  "PA": { name: "Panama", flag: "🇵🇦" },
  "PG": { name: "Papua Nova Gvineja", flag: "🇵🇬" },
  "PY": { name: "Paragvaj", flag: "🇵🇾" },
  "PE": { name: "Peru", flag: "🇵🇪" },
  "PH": { name: "Filipini", flag: "🇵🇭" },
  "PL": { name: "Poljska", flag: "🇵🇱" },
  "PT": { name: "Portugal", flag: "🇵🇹" },
  "QA": { name: "Katar", flag: "🇶🇦" },
  "RO": { name: "Rumunija", flag: "🇷🇴" },
  "RU": { name: "Rusija", flag: "🇷🇺" },
  "RW": { name: "Ruanda", flag: "🇷🇼" },
  "RS": { name: "Srbija", flag: "🇷🇸" },
  "SC": { name: "Sejšeli", flag: "🇸🇨" },
  "SL": { name: "Sijera Leone", flag: "🇸🇱" },
  "SG": { name: "Singapur", flag: "🇸🇬" },
  "SK": { name: "Slovačka", flag: "🇸🇰" },
  "SI": { name: "Slovenija", flag: "🇸🇮" },
  "SB": { name: "Solomonska Ostrva", flag: "🇸🇧" },
  "SO": { name: "Somalija", flag: "🇸🇴" },
  "ZA": { name: "Južnoafrička Republika", flag: "🇿🇦" },
  "KR": { name: "Južna Koreja", flag: "🇰🇷" },
  "ES": { name: "Španija", flag: "🇪🇸" },
  "LK": { name: "Šri Lanka", flag: "🇱🇰" },
  "SD": { name: "Sudan", flag: "🇸🇩" },
  "SR": { name: "Surinam", flag: "🇸🇷" },
  "SE": { name: "Švedska", flag: "🇸🇪" },
  "CH": { name: "Švajcarska", flag: "🇨🇭" },
  "SY": { name: "Sirija", flag: "🇸🇾" },
  "TW": { name: "Tajvan", flag: "🇹🇼" },
  "TJ": { name: "Tadžikistan", flag: "🇹🇯" },
  "TZ": { name: "Tanzanija", flag: "🇹🇿" },
  "TH": { name: "Tajland", flag: "🇹🇭" },
  "TL": { name: "Timor-Leste", flag: "🇹🇱" },
  "TG": { name: "Togo", flag: "🇹🇬" },
  "TO": { name: "Tonga", flag: "🇹🇴" },
  "TT": { name: "Trinidad i Tobago", flag: "🇹🇹" },
  "TN": { name: "Tunis", flag: "🇹🇳" },
  "TR": { name: "Turska", flag: "🇹🇷" },
  "TM": { name: "Turkmenistan", flag: "🇹🇲" },
  "UG": { name: "Uganda", flag: "🇺🇬" },
  "UA": { name: "Ukrajina", flag: "🇺🇦" },
  "AE": { name: "Ujedinjeni Arapski Emirati", flag: "🇦🇪" },
  "SA": { name: "Saudijska Arabija", flag: "🇸🇦" },
  "SN": { name: "Senegal", flag: "🇸🇳" },
  "US": { name: "Sjedinjene Američke Države", flag: "🇺🇸" },
  "UY": { name: "Urugvaj", flag: "🇺🇾" },
  "UZ": { name: "Uzbekistan", flag: "🇺🇿" },
  "VU": { name: "Vanuatu", flag: "🇻🇺" },

  // Članice Velike Britanije kao države sa dvoslovnim kodovima
  "EN": { name: "Engleska", flag: "🏴" },
  "SCO": { name: "Škotska", flag: "🏴" },
  "WL": { name: "Vels", flag: "🏴" },
  "NIR": { name: "Severna Irska", flag: "🇬🇧" },

  // Dodati Kosovo
  "XK": { name: "Kosovo", flag: "🇽🇰" },

  // Dodati Vijetnam
  "VN": { name: "Vijetnam", flag: "🇻🇳" },

  // Dodati Hong Kong
  "HK": { name: "Hong Kong", flag: "🇭🇰" }
};

export default countries;
