const COUNTRY_ALIAS_TO_ISO = {
  "USA": "US",
  "United States": "US",
  "England": "GB-ENG",
  "Scotland": "GB-SCT",
  "Wales": "GB-WLS",
  "Northern Ireland": "GB-NIR",

  "Brazil": "BR",
  "Argentina": "AR",
  "Australia": "AU",
  "Austria": "AT",
  "Belgium": "BE",
  "Bosnia and Herzegovina": "BA",
  "Bulgaria": "BG",
  "Canada": "CA",
  "Chile": "CL",
  "China": "CN",
  "Colombia": "CO",
  "Croatia": "HR",
  "Czech Republic": "CZ",
  "Denmark": "DK",
  "Ecuador": "EC",
  "Egypt": "EG",
  "Finland": "FI",
  "France": "FR",
  "Germany": "DE",
  "Greece": "GR",
  "Hungary": "HU",
  "India": "IN",
  "Indonesia": "ID",
  "Ireland": "IE",
  "Israel": "IL",
  "Italy": "IT",
  "Japan": "JP",
  "Kazakhstan": "KZ",
  "Kosovo": "XK",
  "Lithuania": "LT",
  "Mexico": "MX",
  "Netherlands": "NL",
  "New Zealand": "NZ",
  "Norway": "NO",
  "Paraguay": "PY",
  "Peru": "PE",
  "Poland": "PL",
  "Portugal": "PT",
  "Romania": "RO",
  "Russia": "RU",
  "Saudi Arabia": "SA",
  "Serbia": "RS",
  "Slovakia": "SK",
  "Slovenia": "SI",
  "South Africa": "ZA",
  "South Korea": "KR",
  "Spain": "ES",
  "Sweden": "SE",
  "Switzerland": "CH",
  "Turkey": "TR",
  "Ukraine": "UA",
  "Uruguay": "UY",
  "Vietnam": "VN"
};

export default function countryAliasToISO(country) {
  if (!country) return "";
  return COUNTRY_ALIAS_TO_ISO[country] || "";
}
