import { normalizeCountry } from "./normalizeCountry";

const COUNTRY_ALIAS_TO_ISO = {
  "usa": "US",
  "united states": "US",

  "england": "GB-ENG",
  "scotland": "GB-SCT",
  "wales": "GB-WLS",
  "northern ireland": "GB-NIR",

  "brazil": "BR",
  "argentina": "AR",
  "australia": "AU",
  "austria": "AT",
  "belgium": "BE",
  "bosnia and herzegovina": "BA",
  "bulgaria": "BG",
  "canada": "CA",
  "chile": "CL",
  "china": "CN",
  "colombia": "CO",
  "croatia": "HR",
  "czech republic": "CZ",
  "denmark": "DK",
  "ecuador": "EC",
  "egypt": "EG",
  "finland": "FI",
  "france": "FR",
  "germany": "DE",
  "greece": "GR",
  "hungary": "HU",
  "india": "IN",
  "indonesia": "ID",
  "ireland": "IE",
  "israel": "IL",
  "italy": "IT",
  "japan": "JP",
  "kazakhstan": "KZ",
  "kosovo": "XK",
  "lithuania": "LT",
  "latvia": "LV",
  "mexico": "MX",
  "netherlands": "NL",
  "new zealand": "NZ",
  "norway": "NO",
  "paraguay": "PY",
  "peru": "PE",
  "poland": "PL",
  "portugal": "PT",
  "romania": "RO",
  "russia": "RU",
  "saudi arabia": "SA",
  "serbia": "RS",
  "slovakia": "SK",
  "slovenia": "SI",
  "south africa": "ZA",
  "south korea": "KR",
  "spain": "ES",
  "sweden": "SE",
  "switzerland": "CH",
  "turkey": "TR",
  "ukraine": "UA",
  "uruguay": "UY",
  "vietnam": "VN",

  "iceland": "IS",
  "armenia": "AM",
  "ethiopia": "ET",
  "uzbekistan": "UZ",
  "rwanda": "RW",
  "sierra leone": "SL",
  "tanzania": "TZ",
  "zanzibar": "TZ",
  "south america": "SA"
};

export default function countryAliasToISO(country) {
  if (!country) return "";

  const normalized = normalizeCountry(country);
  return COUNTRY_ALIAS_TO_ISO[normalized] || "";
}
